/*
    Board specific definitions such as pin assignments
    From Purdue Space Program High Altitude, Original author: Griffin Ross
*/

#ifndef BOARD_H
#define BOARD_H

#include "stm32h7xx_hal.h"

// Port to index
#define PIN_PA0 0
#define PIN_PA1 1
#define PIN_PA2 2
#define PIN_PA3 3
#define PIN_PA4 4
#define PIN_PA5 5
#define PIN_PA6 6
#define PIN_PA7 7
#define PIN_PA8 8
#define PIN_PA9 9
#define PIN_PA10 10
#define PIN_PA11 11
#define PIN_PA12 12
#define PIN_PA13 13
#define PIN_PA14 14
#define PIN_PA15 15
#define PIN_PB0 16
#define PIN_PB1 17
#define PIN_PB2 18
#define PIN_PB3 19
#define PIN_PB4 20
#define PIN_PB5 21
#define PIN_PB6 22
#define PIN_PB7 23
#define PIN_PB8 24
#define PIN_PB9 25
#define PIN_PB10 26
#define PIN_PB11 27
#define PIN_PB12 28
#define PIN_PB13 29
#define PIN_PB14 30
#define PIN_PB15 31
#define PIN_PC0 32
#define PIN_PC1 33
#define PIN_PC2 34
#define PIN_PC3 35
#define PIN_PC4 36
#define PIN_PC5 37
#define PIN_PC6 38
#define PIN_PC7 39
#define PIN_PC8 40
#define PIN_PC9 41
#define PIN_PC10 42
#define PIN_PC11 43
#define PIN_PC12 44
#define PIN_PC13 45
#define PIN_PC14 46
#define PIN_PC15 47
#define PIN_PD0 48
#define PIN_PD1 49
#define PIN_PD2 50
#define PIN_PD3 51
#define PIN_PD4 52
#define PIN_PD5 53
#define PIN_PD6 54
#define PIN_PD7 55
#define PIN_PD8 56
#define PIN_PD9 57
#define PIN_PD10 58
#define PIN_PD11 59
#define PIN_PD12 60
#define PIN_PD13 61
#define PIN_PD14 62
#define PIN_PD15 63
#define PIN_PE0 64
#define PIN_PE1 65
#define PIN_PE2 66
#define PIN_PE3 67
#define PIN_PE4 68
#define PIN_PE5 69
#define PIN_PE6 70
#define PIN_PE7 71
#define PIN_PE8 72
#define PIN_PE9 73
#define PIN_PE10 74
#define PIN_PE11 75
#define PIN_PE12 76
#define PIN_PE13 77
#define PIN_PE14 78
#define PIN_PE15 79
#define PIN_PF0 80
#define PIN_PF1 81
#define PIN_PF2 82
#define PIN_PF3 83
#define PIN_PF4 84
#define PIN_PF5 85
#define PIN_PF6 86
#define PIN_PF7 87
#define PIN_PF8 88
#define PIN_PF9 89
#define PIN_PF10 90
#define PIN_PF11 91
#define PIN_PF12 92
#define PIN_PF13 93
#define PIN_PF14 94
#define PIN_PF15 95
#define PIN_PG0 96
#define PIN_PG1 97
#define PIN_PG2 98
#define PIN_PG3 99
#define PIN_PG4 100
#define PIN_PG5 101
#define PIN_PG6 102
#define PIN_PG7 103
#define PIN_PG8 104
#define PIN_PG9 105
#define PIN_PG10 106
#define PIN_PG11 107
#define PIN_PG12 108
#define PIN_PG13 109
#define PIN_PG14 110
#define PIN_PG15 111
#define PIN_PH0 112
#define PIN_PH1 113

#define PIN_MAX PIN_PK7

__attribute__((unused)) static GPIO_TypeDef* BOARD_GPIO_PORT[] = {
    GPIOA, GPIOB, GPIOC, GPIOD, GPIOE, GPIOF,
    GPIOG, GPIOH, GPIOI, GPIOJ, GPIOK};

// Physical pin to MODER mask
__attribute__((unused)) static uint32_t GPIO_PIN_TO_MODEMASK[] = {
    GPIO_MODER_MODER0_Msk,  GPIO_MODER_MODER1_Msk,  GPIO_MODER_MODER2_Msk,
    GPIO_MODER_MODER3_Msk,  GPIO_MODER_MODER4_Msk,  GPIO_MODER_MODER5_Msk,
    GPIO_MODER_MODER6_Msk,  GPIO_MODER_MODER7_Msk,  GPIO_MODER_MODER8_Msk,
    GPIO_MODER_MODER9_Msk,  GPIO_MODER_MODER10_Msk, GPIO_MODER_MODER11_Msk,
    GPIO_MODER_MODER12_Msk, GPIO_MODER_MODER13_Msk, GPIO_MODER_MODER14_Msk,
    GPIO_MODER_MODER15_Msk, GPIO_MODER_MODER0_Msk,  GPIO_MODER_MODER1_Msk,
    GPIO_MODER_MODER2_Msk,  GPIO_MODER_MODER3_Msk,  GPIO_MODER_MODER4_Msk,
    GPIO_MODER_MODER5_Msk,  GPIO_MODER_MODER6_Msk,  GPIO_MODER_MODER7_Msk,
    GPIO_MODER_MODER8_Msk,  GPIO_MODER_MODER9_Msk,  GPIO_MODER_MODER10_Msk,
    GPIO_MODER_MODER11_Msk, GPIO_MODER_MODER12_Msk, GPIO_MODER_MODER13_Msk,
    GPIO_MODER_MODER14_Msk, GPIO_MODER_MODER15_Msk, GPIO_MODER_MODER0_Msk,
    GPIO_MODER_MODER1_Msk,  GPIO_MODER_MODER2_Msk,  GPIO_MODER_MODER3_Msk,
    GPIO_MODER_MODER4_Msk,  GPIO_MODER_MODER5_Msk,  GPIO_MODER_MODER6_Msk,
    GPIO_MODER_MODER7_Msk,  GPIO_MODER_MODER8_Msk,  GPIO_MODER_MODER9_Msk,
    GPIO_MODER_MODER10_Msk, GPIO_MODER_MODER11_Msk, GPIO_MODER_MODER12_Msk,
    GPIO_MODER_MODER13_Msk, GPIO_MODER_MODER14_Msk, GPIO_MODER_MODER15_Msk,
    GPIO_MODER_MODER0_Msk,  GPIO_MODER_MODER1_Msk,  GPIO_MODER_MODER2_Msk,
    GPIO_MODER_MODER3_Msk,  GPIO_MODER_MODER4_Msk,  GPIO_MODER_MODER5_Msk,
    GPIO_MODER_MODER6_Msk,  GPIO_MODER_MODER7_Msk,  GPIO_MODER_MODER8_Msk,
    GPIO_MODER_MODER9_Msk,  GPIO_MODER_MODER10_Msk, GPIO_MODER_MODER11_Msk,
    GPIO_MODER_MODER12_Msk, GPIO_MODER_MODER13_Msk, GPIO_MODER_MODER14_Msk,
    GPIO_MODER_MODER15_Msk, GPIO_MODER_MODER0_Msk,  GPIO_MODER_MODER1_Msk,
    GPIO_MODER_MODER2_Msk,  GPIO_MODER_MODER3_Msk,  GPIO_MODER_MODER4_Msk,
    GPIO_MODER_MODER5_Msk,  GPIO_MODER_MODER6_Msk,  GPIO_MODER_MODER7_Msk,
    GPIO_MODER_MODER8_Msk,  GPIO_MODER_MODER9_Msk,  GPIO_MODER_MODER10_Msk,
    GPIO_MODER_MODER11_Msk, GPIO_MODER_MODER12_Msk, GPIO_MODER_MODER13_Msk,
    GPIO_MODER_MODER14_Msk, GPIO_MODER_MODER15_Msk, GPIO_MODER_MODER0_Msk,
    GPIO_MODER_MODER1_Msk,  GPIO_MODER_MODER2_Msk,  GPIO_MODER_MODER3_Msk,
    GPIO_MODER_MODER4_Msk,  GPIO_MODER_MODER5_Msk,  GPIO_MODER_MODER6_Msk,
    GPIO_MODER_MODER7_Msk,  GPIO_MODER_MODER8_Msk,  GPIO_MODER_MODER9_Msk,
    GPIO_MODER_MODER10_Msk, GPIO_MODER_MODER11_Msk, GPIO_MODER_MODER12_Msk,
    GPIO_MODER_MODER13_Msk, GPIO_MODER_MODER14_Msk, GPIO_MODER_MODER15_Msk,
    GPIO_MODER_MODER0_Msk,  GPIO_MODER_MODER1_Msk,  GPIO_MODER_MODER2_Msk,
    GPIO_MODER_MODER3_Msk,  GPIO_MODER_MODER4_Msk,  GPIO_MODER_MODER5_Msk,
    GPIO_MODER_MODER6_Msk,  GPIO_MODER_MODER7_Msk,  GPIO_MODER_MODER8_Msk,
    GPIO_MODER_MODER9_Msk,  GPIO_MODER_MODER10_Msk, GPIO_MODER_MODER11_Msk,
    GPIO_MODER_MODER12_Msk, GPIO_MODER_MODER13_Msk, GPIO_MODER_MODER14_Msk,
    GPIO_MODER_MODER15_Msk, GPIO_MODER_MODER0_Msk,  GPIO_MODER_MODER1_Msk,
};

// Physical pin to MODER pos
__attribute__((unused)) static uint32_t GPIO_PIN_TO_MODEPOS[] = {
    GPIO_MODER_MODER0_Pos,  GPIO_MODER_MODER1_Pos,  GPIO_MODER_MODER2_Pos,
    GPIO_MODER_MODER3_Pos,  GPIO_MODER_MODER4_Pos,  GPIO_MODER_MODER5_Pos,
    GPIO_MODER_MODER6_Pos,  GPIO_MODER_MODER7_Pos,  GPIO_MODER_MODER8_Pos,
    GPIO_MODER_MODER9_Pos,  GPIO_MODER_MODER10_Pos, GPIO_MODER_MODER11_Pos,
    GPIO_MODER_MODER12_Pos, GPIO_MODER_MODER13_Pos, GPIO_MODER_MODER14_Pos,
    GPIO_MODER_MODER15_Pos, GPIO_MODER_MODER0_Pos,  GPIO_MODER_MODER1_Pos,
    GPIO_MODER_MODER2_Pos,  GPIO_MODER_MODER3_Pos,  GPIO_MODER_MODER4_Pos,
    GPIO_MODER_MODER5_Pos,  GPIO_MODER_MODER6_Pos,  GPIO_MODER_MODER7_Pos,
    GPIO_MODER_MODER8_Pos,  GPIO_MODER_MODER9_Pos,  GPIO_MODER_MODER10_Pos,
    GPIO_MODER_MODER11_Pos, GPIO_MODER_MODER12_Pos, GPIO_MODER_MODER13_Pos,
    GPIO_MODER_MODER14_Pos, GPIO_MODER_MODER15_Pos, GPIO_MODER_MODER0_Pos,
    GPIO_MODER_MODER1_Pos,  GPIO_MODER_MODER2_Pos,  GPIO_MODER_MODER3_Pos,
    GPIO_MODER_MODER4_Pos,  GPIO_MODER_MODER5_Pos,  GPIO_MODER_MODER6_Pos,
    GPIO_MODER_MODER7_Pos,  GPIO_MODER_MODER8_Pos,  GPIO_MODER_MODER9_Pos,
    GPIO_MODER_MODER10_Pos, GPIO_MODER_MODER11_Pos, GPIO_MODER_MODER12_Pos,
    GPIO_MODER_MODER13_Pos, GPIO_MODER_MODER14_Pos, GPIO_MODER_MODER15_Pos,
    GPIO_MODER_MODER0_Pos,  GPIO_MODER_MODER1_Pos,  GPIO_MODER_MODER2_Pos,
    GPIO_MODER_MODER3_Pos,  GPIO_MODER_MODER4_Pos,  GPIO_MODER_MODER5_Pos,
    GPIO_MODER_MODER6_Pos,  GPIO_MODER_MODER7_Pos,  GPIO_MODER_MODER8_Pos,
    GPIO_MODER_MODER9_Pos,  GPIO_MODER_MODER10_Pos, GPIO_MODER_MODER11_Pos,
    GPIO_MODER_MODER12_Pos, GPIO_MODER_MODER13_Pos, GPIO_MODER_MODER14_Pos,
    GPIO_MODER_MODER15_Pos, GPIO_MODER_MODER0_Pos,  GPIO_MODER_MODER1_Pos,
    GPIO_MODER_MODER2_Pos,  GPIO_MODER_MODER3_Pos,  GPIO_MODER_MODER4_Pos,
    GPIO_MODER_MODER5_Pos,  GPIO_MODER_MODER6_Pos,  GPIO_MODER_MODER7_Pos,
    GPIO_MODER_MODER8_Pos,  GPIO_MODER_MODER9_Pos,  GPIO_MODER_MODER10_Pos,
    GPIO_MODER_MODER11_Pos, GPIO_MODER_MODER12_Pos, GPIO_MODER_MODER13_Pos,
    GPIO_MODER_MODER14_Pos, GPIO_MODER_MODER15_Pos, GPIO_MODER_MODER0_Pos,
    GPIO_MODER_MODER1_Pos,  GPIO_MODER_MODER2_Pos,  GPIO_MODER_MODER3_Pos,
    GPIO_MODER_MODER4_Pos,  GPIO_MODER_MODER5_Pos,  GPIO_MODER_MODER6_Pos,
    GPIO_MODER_MODER7_Pos,  GPIO_MODER_MODER8_Pos,  GPIO_MODER_MODER9_Pos,
    GPIO_MODER_MODER10_Pos, GPIO_MODER_MODER11_Pos, GPIO_MODER_MODER12_Pos,
    GPIO_MODER_MODER13_Pos, GPIO_MODER_MODER14_Pos, GPIO_MODER_MODER15_Pos,
    GPIO_MODER_MODER0_Pos,  GPIO_MODER_MODER1_Pos,  GPIO_MODER_MODER2_Pos,
    GPIO_MODER_MODER3_Pos,  GPIO_MODER_MODER4_Pos,  GPIO_MODER_MODER5_Pos,
    GPIO_MODER_MODER6_Pos,  GPIO_MODER_MODER7_Pos,  GPIO_MODER_MODER8_Pos,
    GPIO_MODER_MODER9_Pos,  GPIO_MODER_MODER10_Pos, GPIO_MODER_MODER11_Pos,
    GPIO_MODER_MODER12_Pos, GPIO_MODER_MODER13_Pos, GPIO_MODER_MODER14_Pos,
    GPIO_MODER_MODER15_Pos, GPIO_MODER_MODER0_Pos,  GPIO_MODER_MODER1_Pos,
};

// Pin to port
#define BOARD_GPIO_PORT(pin) BOARD_GPIO_PORT[pin >> 4]

// Pin to index
#define BOARD_GPIO_PIN(pin) (1 << (pin & 0xF))

// Pin to MODER mask
#define BOARD_GPIO_MODER_MASK(pin) GPIO_PIN_TO_MODEMASK[pin]

#define BOARD_GPIO_MODER_POS(pin) GPIO_PIN_TO_MODEPOS[pin]

// Pin aliases

// LEDs
#define PIN_RED PIN_PD3
#define PIN_YEL PIN_PD4
#define PIN_GRN PIN_PD5
#define PIN_BLU PIN_PD7

// Steppers
#define PIN_TURNTABLE_DIR PIN_PB4
#define PIN_GANTRY_DIR PIN_PB5
#define PIN_EXTRUDER_DIR PIN_PB6
#define PIN_REVOLUTE_DIR PIN_PB7

#define PIN_TURNTABLE_STEP PIN_PD15
#define PIN_GANTRY_STEP PIN_PD14
#define PIN_EXTRUDER_STEP PIN_PD13
#define PIN_REVOLUTE_STEP PIN_PD12

// Cutter
#define PIN_CUTTER PIN_PC1

// Start Marlin

// Switches
#define PIN_TURNTABLE_MIN PIN_PG10
#define PIN_GANTRY_MIN PIN_PG11
#define PIN_EXTRUDER_MIN PIN_PG12
#define PIN_REVOLUTE_MIN PIN_PG15

// Dummy X
#define X_STEP_PIN -1
#define X_DIR_PIN -1
#define X_ENABLE_PIN -1
#define X_MIN_PIN -1

// Turntable
#define J_STEP_PIN PIN_TURNTABLE_STEP
#define J_DIR_PIN PIN_TURNTABLE_DIR
#define J_ENABLE_PIN -1
// #define J_MIN_PIN PIN_TURNTABLE_MIN
#define J_MIN_PIN -1

// Extruder
#define Y_STEP_PIN PIN_EXTRUDER_STEP
#define Y_DIR_PIN PIN_EXTRUDER_DIR
#define Y_ENABLE_PIN -1
#define Y_MIN_PIN PIN_EXTRUDER_MIN

// Gantry
#define Z_STEP_PIN PIN_GANTRY_STEP
#define Z_DIR_PIN PIN_GANTRY_DIR
#define Z_ENABLE_PIN -1
#define Z_MIN_PIN PIN_GANTRY_MIN

// Wrist/Revolute
#define I_STEP_PIN PIN_REVOLUTE_STEP
#define I_DIR_PIN PIN_REVOLUTE_DIR
#define I_ENABLE_PIN -1
#define I_MIN_PIN PIN_REVOLUTE_MIN
// #define I_MIN_PIN -1

// End Marlin

// Touchscreen driver
#define PIN_TS_SDA PIN_PF0
#define PIN_TS_SCL PIN_PF1
#define PIN_TS_NRST PIN_PF2
#define PIN_TS_INT PIN_PF3

// Backlight
#define PIN_BL_EN PIN_PB13
#define PIN_BL_DIM PIN_PB14
#define PIN_BL_DISC PIN_PB15

// LCD (all AF14 unless specified)
#define PIN_LCD_DISP PIN_PA0
#define PIN_LCD_DE PIN_PE13
#define PIN_LCD_PCLK PIN_PE14
#define PIN_LCD_HSYNC PIN_PC6
#define PIN_LCD_VSYNC PIN_PA4
#define PIN_LCD_R0 PIN_PG13
#define PIN_LCD_R1 PIN_PA2
#define PIN_LCD_R2 PIN_PA1
#define PIN_LCD_R3 PIN_PB0  // AF9
#define PIN_LCD_R4 PIN_PA5
#define PIN_LCD_R5 PIN_PC0
#define PIN_LCD_R6 PIN_PB1  // AF9
#define PIN_LCD_R7 PIN_PE15
#define PIN_LCD_G0 PIN_PE5
#define PIN_LCD_G1 PIN_PE6
#define PIN_LCD_G2 PIN_PA6
#define PIN_LCD_G3 PIN_PE11
#define PIN_LCD_G4 PIN_PB10
#define PIN_LCD_G5 PIN_PB11
#define PIN_LCD_G6 PIN_PC7
#define PIN_LCD_G7 PIN_PG8
#define PIN_LCD_B0 PIN_PE4
#define PIN_LCD_B1 PIN_PA10
#define PIN_LCD_B2 PIN_PD6
#define PIN_LCD_B3 PIN_PD10
#define PIN_LCD_B4 PIN_PE12
#define PIN_LCD_B5 PIN_PA3
#define PIN_LCD_B6 PIN_PB8
#define PIN_LCD_B7 PIN_PB9

// SD
#define PIN_SD_CD PIN_PD1
#define PIN_SD_CLK PIN_PC12
#define PIN_SD_CMD PIN_PD2
#define PIN_SD_D0 PIN_PC8
#define PIN_SD_D1 PIN_PC9
#define PIN_SD_D2 PIN_PC10
#define PIN_SD_D3 PIN_PC11

// Door Switch
#define PIN_DOOR PIN_PB3

#endif  // BOARD_H