; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = core_m7, core_m4

[env:core_m7]
platform = ststm32
board = disco_h747xi
framework = stm32cube
build_flags = 
    -std=c++17
    -DCORE_CM7
build_src_filter = +<M7> -<M4>
board_build.ldscript = src/M7/linkerscript.ld
upload_command = upload_m7.bat
debug_tool = stlink
debug_server = 
    ${platformio.packages_dir}/tool-openocd/bin/openocd
    -f
    openocd.cfg

[env:core_m4]
platform = ststm32
board = disco_h747xi
framework = stm32cube
build_flags = 
    -std=c++17
    -DCORE_CM4
build_src_filter = +<M4> -<M7>
board_build.ldscript = src/M4/linkerscript.ld
upload_command = upload_m4.bat