; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = core_m7, core_m4

[env:common]
platform = ststm32
board = disco_h747xi
framework = stm32cube
build_flags = 
    -std=c++17
    -D'UNUSED(x)=(void)x'
    -Wl,-u,_printf_float
build_src_flags =
    -Wall -Wextra -Werror
    -Wno-unused-function
    -Wno-unused-parameter
    -Wno-expansion-to-defined
extra_scripts = 
    pre:scripts/dependencies.py
    pre:scripts/convert_bmp_to_header.py
    pre:scripts/convert_ttf_to_header.py

[env:common_no_extflash]
platform = ststm32
board = disco_h747xi
framework = stm32cube
build_flags = 
    -std=c++17
    -D'UNUSED(x)=(void)x'
    -Wl,-u,_printf_float
build_src_flags =
    -Wall -Wextra -Werror
    -Wno-unused-function
    -Wno-unused-parameter
    -Wno-expansion-to-defined

[env:core_m7]
extends = env:common
build_flags = ${env:common.build_flags}
    -DCORE_CM7
build_src_filter = +<*> +<M7> -<M4>
board_build.ldscript = src/M7/linkerscript.ld
upload_command = upload_m7.bat
debug_tool = custom
debug_port = :61234
debug_server =
    C:\ST\STM32CubeIDE_2.1.1\STM32CubeIDE\plugins\com.st.stm32cube.ide.mcu.externaltools.stlink-gdb-server.win32_2.2.400.202601091506\tools\bin\ST-LINK_gdbserver.exe
    -cp C:\ST\STM32CubeIDE_2.1.1\STM32CubeIDE\plugins\com.st.stm32cube.ide.mcu.externaltools.cubeprogrammer.win32_2.2.400.202601091506\tools\bin
    -v
    -d
	-m 0
debug_init_cmds =
  define pio_reset_halt_target
      monitor reset
      monitor halt
  end
  define pio_reset_run_target
      monitor reset
  end
  target extended-remote $DEBUG_PORT
  $LOAD_CMDS
  pio_reset_halt_target
  $INIT_BREAK

[env:core_m7_no_extflash]
extends = env:common_no_extflash
build_flags = ${env:common_no_extflash.build_flags}
    -DCORE_CM7
build_src_filter = +<*> +<M7> -<M4>
board_build.ldscript = src/M7/linkerscript_no_extflash.ld
upload_command = upload_m7_no_extflash.bat
debug_tool = custom
debug_port = :61234
debug_server =
    C:\ST\STM32CubeIDE_2.1.1\STM32CubeIDE\plugins\com.st.stm32cube.ide.mcu.externaltools.stlink-gdb-server.win32_2.2.400.202601091506\tools\bin\ST-LINK_gdbserver.exe
    -cp C:\ST\STM32CubeIDE_2.1.1\STM32CubeIDE\plugins\com.st.stm32cube.ide.mcu.externaltools.cubeprogrammer.win32_2.2.400.202601091506\tools\bin
    -v
    -d
	-m 0
debug_init_cmds =
  define pio_reset_halt_target
      monitor reset
      monitor halt
  end
  define pio_reset_run_target
      monitor reset
  end
  target extended-remote $DEBUG_PORT
  $LOAD_CMDS
  pio_reset_halt_target
  $INIT_BREAK

[env:core_m4]
extends = env:common_no_extflash
build_flags = ${env:common_no_extflash.build_flags}
    -DCORE_CM4
build_src_filter = +<*> +<M4> -<M7>
board_build.ldscript = src/M4/linkerscript.ld
upload_command = upload_m4.bat
debug_tool = custom
debug_port = :61234
debug_server =
    C:\ST\STM32CubeIDE_2.1.1\STM32CubeIDE\plugins\com.st.stm32cube.ide.mcu.externaltools.stlink-gdb-server.win32_2.2.400.202601091506\tools\bin\ST-LINK_gdbserver.exe
    -cp C:\ST\STM32CubeIDE_2.1.1\STM32CubeIDE\plugins\com.st.stm32cube.ide.mcu.externaltools.cubeprogrammer.win32_2.2.400.202601091506\tools\bin
    -v
    -d
	-m 3
debug_init_cmds =
  define pio_reset_halt_target
      monitor reset
      monitor halt
  end
  define pio_reset_run_target
      monitor reset
  end
  target extended-remote $DEBUG_PORT
  $LOAD_CMDS
  pio_reset_halt_target
  $INIT_BREAK